/* eslint-disable @next/next/no-sync-scripts */

import Providers from "../components/poroviders/Providers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Slide, ToastContainer } from "react-toastify";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dhaka super market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position="bottom-right"
          transition={Slide}
          autoClose={3000}
          hideProgressBar
          newestOnTop
          closeOnClick
          rtl={false}
          pauseOnFocusLoss={false}
          draggable
          pauseOnHover
          toastClassName={"w-[100%] sm:w-[400px] rounded-[4px] font-inter font-medium text-sm  text-neutral-900 shadow-toast-shadow p-[10px] min-h-0}"} aria-label={undefined}        />
        <Providers>{children}</Providers>
        <script src="/runtime-env.js" />
      </body>
    </html>
  );
}
